<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5983" started-at="2016-04-26T15:24:42Z" finished-at="2016-04-26T15:24:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5983" started-at="2016-04-26T15:24:42Z" finished-at="2016-04-26T15:24:48Z">
      <class name="org.quinnox.validateData.ValidateDataTest">
        <test-method status="PASS" signature="configBeforeClass()[pri:0, instance:org.quinnox.validateData.ValidateDataTest@4eb49448]" name="configBeforeClass" is-config="true" duration-ms="0" started-at="2016-04-26T20:54:46Z" finished-at="2016-04-26T20:54:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeClass -->
        <test-method status="PASS" signature="validatePostRequest()[pri:0, instance:org.quinnox.validateData.ValidateDataTest@4eb49448]" name="validatePostRequest" duration-ms="439" started-at="2016-04-26T20:54:46Z" finished-at="2016-04-26T20:54:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePostRequest -->
      </class> <!-- org.quinnox.validateData.ValidateDataTest -->
      <class name="org.quinnox.validateInvalidPostData.ValidateInvalidPostData">
        <test-method status="PASS" signature="configBeforeClass()[pri:0, instance:org.quinnox.validateInvalidPostData.ValidateInvalidPostData@31732b56]" name="configBeforeClass" is-config="true" duration-ms="0" started-at="2016-04-26T20:54:47Z" finished-at="2016-04-26T20:54:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeClass -->
        <test-method status="FAIL" signature="validateInavlidPostRequest()[pri:0, instance:org.quinnox.validateInvalidPostData.ValidateInvalidPostData@31732b56]" name="validateInavlidPostRequest" duration-ms="914" started-at="2016-04-26T20:54:47Z" finished-at="2016-04-26T20:54:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[You are trying to post invalid data!! expected [200] but found [202]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: You are trying to post invalid data!! expected [200] but found [202]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.quinnox.validateInvalidPostData.ValidateInvalidPostData.validateInavlidPostRequest(ValidateInvalidPostData.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInavlidPostRequest -->
      </class> <!-- org.quinnox.validateInvalidPostData.ValidateInvalidPostData -->
      <class name="org.quinnox.verifyRest.VerifyRestTest">
        <test-method status="PASS" signature="configBeforeClass()[pri:0, instance:org.quinnox.verifyRest.VerifyRestTest@65612c8f]" name="configBeforeClass" is-config="true" duration-ms="42" started-at="2016-04-26T20:54:42Z" finished-at="2016-04-26T20:54:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeClass -->
        <test-method status="PASS" signature="testRestApi()[pri:0, instance:org.quinnox.verifyRest.VerifyRestTest@65612c8f]" name="testRestApi" duration-ms="4558" started-at="2016-04-26T20:54:42Z" finished-at="2016-04-26T20:54:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRestApi -->
      </class> <!-- org.quinnox.verifyRest.VerifyRestTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
